import matplotlib.pyplot as plt
import os
import numpy as np

os.chdir("C:/Users/Tannlin User/Documents/Tannlin Internship 2020/Side Profiles/MicroVue Measurements/Supersonic Nozzle")
os.getcwd()

step = 0.1
N_step = 60

# Load Data 50 | 100 | 150 | 200 | 250

XY_SS= np.zeros((7, 61))

XY_SS[0, :] = np.loadtxt(fname="XY_H50.txt", delimiter=',')
XY_SS[1, :] = np.loadtxt(fname="XY_H150.txt", delimiter=',')
XY_SS[2, :] = np.loadtxt(fname="XY_H250.txt", delimiter=',')
XY_SS[3, :] = np.loadtxt(fname="XY_H350.txt", delimiter=',')
XY_SS[4, :] = np.loadtxt(fname="XY_H450.txt", delimiter=',')
XY_SS[5, :] = np.loadtxt(fname="XY_H550.txt", delimiter=',')
XY_SS[6, :] = np.loadtxt(fname="XY_H650.txt", delimiter=',')

Y = np.linspace(0, 6, num=len(XY_SS[0, :]))
Z = np.linspace(50, 650, num=7)
Y_sample = np.linspace(0,6,num=100)

##
Var = np.zeros(7)
Ave = np.zeros(7)
deg = 3
Z_sample = np.linspace(50, 650, num=100)
Coefs_SS = np.zeros((7,deg+1))
LoBF_SS = np.zeros((7,100))

for i in range(0, 7):
    Var[i] = np.var(XY_SS[i, :])
    Ave[i] = np.mean(XY_SS[i, :])
    Coefs_SS[i,:] = np.polyfit(Y,XY_SS[i,:],deg)
    LoBF_SS[i,:] = np.polyval(Coefs_SS[i,:], Y_sample)

plot1 = plt.figure(1)
plt.scatter(Y,1000*XY_SS[0,:],color='r',label='50 um')
plt.scatter(Y,1000*XY_SS[1,:],color='g',label='150 um')
plt.scatter(Y,1000*XY_SS[2,:],color='b',label='250 um')
plt.scatter(Y,1000*XY_SS[3,:],color='m',label='350 um')
plt.legend()
plt.plot(Y_sample,1000*LoBF_SS[0,:],color='r', linestyle='dashed')
plt.plot(Y_sample,1000*LoBF_SS[1,:],color='g', linestyle='dashed')
plt.plot(Y_sample,1000*LoBF_SS[2,:],color='b', linestyle='dashed')
plt.plot(Y_sample,1000*LoBF_SS[3,:],color='m', linestyle='dashed')
plt.xlabel('Distance (mm)')
plt.ylabel('Surface Roughness (um)')
plt.legend()
plt.grid()
plt.title('Outer Surface Measurements for 50<H<350 um')

plot2 = plt.figure(2)
plt.scatter(Y,1000*XY_SS[4,:],color='r',label='450 um')
plt.scatter(Y,1000*XY_SS[5,:],color='g',label='550 um')
plt.scatter(Y,1000*XY_SS[6,:],color='b',label='650 um')
plt.legend()
plt.plot(Y_sample,1000*LoBF_SS[4,:],color='r', linestyle='dashed')
plt.plot(Y_sample,1000*LoBF_SS[5,:],color='g', linestyle='dashed')
plt.plot(Y_sample,1000*LoBF_SS[6,:],color='b', linestyle='dashed')
plt.xlabel('Distance (mm)')
plt.ylabel('Surface Roughness (um)')
plt.legend(loc='upper right')
plt.grid()
plt.title('Outer Surface Measurements for 450<H<650 um')

##plot2 = plt.figure(2)
##plt.scatter(Y,1000*XY_90[1,:],color='r',label='90 deg Chamfer')
##plt.scatter(Y,1000*XY_R15[1,:],color='g',label='1.5 mm Radius')
##plt.scatter(Y,1000*XY_R5[1,:],color='b',label='5 mm Radius')
##plt.xlabel('Distance (mm)')
##plt.ylabel('Surface Roughness (um)')
##plt.legend()
##plt.grid()
##plt.title('Outer Surface Measurements for H = 100 um')
##
##plot3 = plt.figure(3)
##plt.scatter(Y,1000*XY_90[2,:],color='r',label='90 deg Chamfer')
##plt.scatter(Y,1000*XY_R15[2,:],color='g',label='1.5 mm Radius')
##plt.scatter(Y,1000*XY_R5[2,:],color='b',label='5 mm Radius')
##plt.xlabel('Distance (mm)')
##plt.ylabel('Surface Roughness (um)')
##plt.legend()
##plt.grid()
##plt.title('Outer Surface Measurements for H = 150 um')
##
##plot4 = plt.figure(4)
##plt.scatter(Y,1000*XY_90[3,:],color='r',label='90 deg Chamfer')
##plt.scatter(Y,1000*XY_R15[3,:],color='g',label='1.5 mm Radius')
##plt.scatter(Y,1000*XY_R5[3,:],color='b',label='5 mm Radius')
##plt.xlabel('Distance (mm)')
##plt.ylabel('Surface Roughness (um)')
##plt.legend()
##plt.grid()
##plt.title('Outer Surface Measurements for H = 200 um')
##
##plot5 = plt.figure(5)
##plt.scatter(Y,1000*XY_90[4,:],color='r',label='90 deg Chamfer')
##plt.scatter(Y,1000*XY_R15[4,:],color='g',label='1.5 mm Radius')
##plt.scatter(Y,1000*XY_R5[4,:],color='b',label='5 mm Radius')
##plt.xlabel('Distance (mm)')
##plt.ylabel('Surface Roughness (um)')
##plt.legend()
##plt.grid()
##plt.title('Outer Surface Measurements for H = 250 um')
##
##plot6 = plt.figure(6)
##plt.scatter(Y,1000*XY_90[5,:],color='r',label='90 deg Chamfer')
##plt.scatter(Y,1000*XY_R5[5,:],color='b',label='5 mm Radius')
##plt.xlabel('Distance (mm)')
##plt.ylabel('Surface Roughness (um)')
##plt.legend()
##plt.grid()
##plt.title('Outer Surface Measurements for H = 300 um')
##
##plot7 = plt.figure(7)
##plt.scatter(Y,1000*XY_90[6,:],color='r',label='90 deg Chamfer')
##plt.scatter(Y,1000*XY_R5[6,:],color='b',label='5 mm Radius')
##plt.xlabel('Distance (mm)')
##plt.ylabel('Surface Roughness (um)')
##plt.legend()
##plt.grid()
##plt.title('Outer Surface Measurements for H = 350 um')
##
##plot8 = plt.figure(8)
##plt.scatter(Y,1000*XY_90[7,:],color='r',label='90 deg Chamfer')
##plt.scatter(Y,1000*XY_R15[7,:],color='g',label='1.5 mm Radius')
##plt.scatter(Y,1000*XY_R5[7,:],color='b',label='5 mm Radius')
##plt.xlabel('Distance (mm)')
##plt.ylabel('Surface Roughness (um)')
##plt.legend()
##plt.grid()
##plt.title('Outer Surface Measurements for H = 400 um')

plot9 = plt.figure(9)
plt.plot(Z, Var,color='b')
plt.xlabel('Run Height (um)')
plt.ylabel('Variance')
plt.legend()
plt.grid()
plt.title('Variance of Outer Surface Measurements')

plt.show()
##
##plot10 = plt.figure(10)
##plt.plot(Z,Ave_90*1000,color='r',label='90 deg Chamfer')
##plt.plot(Z,Ave_R15*1000,color='g',label='1.5 mm Radius')
##plt.plot(Z,Ave_R5*1000,color='b',label='5 mm Radius')
##plt.xlabel('Run Height (um)')
##plt.ylabel('Mean Surface Roughness (um)')
##plt.legend()
##plt.grid()
##plt.title('Mean of Outer Surface Measurements')
##plt.show()
##
